### ISSUE TITLE
Zap-Android cannot connect to BTCPayServer: Invalid Connection Information

### ISSUE THREAD

**Issue by pretyflaco** [LN-Zap/zap-android#32]
**Description of the issue**
BTCPay exposes LND's GRPC service for outside consumption. It allows to connect external software, like Zap Android or Pebble Wallet, via QR Code. When scanned with Zap Android, app returns "Invalid Connection Information"

**Environment**
Device: OnePlus 3
Android Version: 9
BTCPayServer Version: 1.0.3.114
LND Version: 0.6.1-beta
QR Code created using BTCPayServer UI

**Steps to reproduce**
1. Install the application
2. Connect to Remote Node
3. Scan GRPC information in BTCPayServer from QR Code
4. See Error: Invalid Connection Information

**Expected behavior**
Application connects to node.

**Comment by michaelWuensch** [comment]
Thanks for your report.
BTC Pay server connection is not yet supported. We hope to implement it as soon as possible.

**Comment by pieman64** [comment]
@michaelWuensch we are also looking forward to BTC Pay server support.

**Comment by maraph** [comment]
@pretyflaco @pieman64

We have released the newest Zap version **0.2.3-alpha** to the PlayStore. 🎉 
Link: https://play.google.com/store/apps/details?id=zapsolutions.zap
Now, you should be able to connect to your BtcPay Server.

You are able to use the QR-Code, the `config=` url scheme or the full configuration.
Feedback is as always very welcome! 💬 👍

**Comment by pieman64** [comment]
Tried updated app earlier today. All the QR codes I could find for BTCPay failed.

**Comment by michaelWuensch** [comment]
Thanks for testing. We are sorry you still have problems, it worked on our test systems. Can you give more context? 
What is the error message you see?

**Comment by pieman64** [comment]
@michaelWuensch when I scan the QR code it shows as not compatible.

I am using c-lightning with BTCPay as my node is tied to some Lapps. Does your integration only work for LND implementation of Lightning? If so do you have plans to support c-lightning?

**Comment by michaelWuensch** [comment]
Yes, that is the reason, we only support LND so far.
We might support c-lightning some day, but this is probably far in the future.
